### PR TITLE
Allow MutableMapping for python >= 3.10

### PR DESCRIPTION
**Pull request by jjanier**
Python 3.10 MutableMapping moved from collections to collections.abc

### CODE REVIEW

**Comment by skybber** [comment]
Thanks!

**Comment by jjanier** [comment]
@skybber are you planning to release this to pypi ?

**Comment by skybber** [comment]
I'll do it during the day

**Comment by skybber** [comment]
fixed in v4.0.2 https://pypi.org/project/udger/

**Comment by jjanier** [comment]
Great, this is really helpful. Thanks again.

**Pull request merged**
